# Generated by Django 2.0 on 2018-05-08 02:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobbyname', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='stream/static/images')),
                ('description', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='stream/static/images')),
            ],
        ),
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='streamer_info', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Streamer_lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobbies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lobby_of_streamer', to='stream.Lobby')),
                ('streamers', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='streamer_in_lobby', to='stream.Streamer')),
            ],
        ),
        migrations.CreateModel(
            name='Subcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='publishers', to='stream.Streamer')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='stream.Streamer')),
            ],
        ),
        migrations.AddField(
            model_name='stream',
            name='streamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stream.Streamer'),
        ),
    ]
