# Generated by Django 2.0.5 on 2018-05-04 03:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobbyname', models.CharField(max_length=50)),
                ('logo', models.ImageField(upload_to=None)),
                ('description', models.CharField(max_length=200)),
                ('streamers', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=200)),
                ('thumbnail', models.ImageField(upload_to=None)),
            ],
        ),
        migrations.CreateModel(
            name='Streamer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobby', models.CharField(max_length=50)),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Streamer_lobby',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lobbies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='streaming.Lobby')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='streaming.Streamer')),
            ],
        ),
        migrations.AddField(
            model_name='stream',
            name='streamer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='streaming.Streamer'),
        ),
    ]
