# Generated by Django 2.0.5 on 2018-05-04 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='streamers',
        ),
        migrations.RemoveField(
            model_name='stream',
            name='description',
        ),
        migrations.RemoveField(
            model_name='streamer',
            name='lobby',
        ),
        migrations.RemoveField(
            model_name='streamer_lobby',
            name='user',
        ),
        migrations.AddField(
            model_name='streamer_lobby',
            name='users',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='name', to='streaming.Streamer'),
        ),
        migrations.AlterField(
            model_name='streamer_lobby',
            name='lobbies',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='streamers', to='streaming.Lobby'),
        ),
    ]
