# Generated by Django 2.0 on 2018-05-08 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stream', '0002_notification'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subcription',
            new_name='Subscription',
        ),
    ]
