# Generated by Django 2.0.5 on 2018-05-04 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_auto_20180504_0518'),
    ]

    operations = [
        migrations.RenameField(
            model_name='streamer_lobby',
            old_name='users',
            new_name='streamers',
        ),
        migrations.AlterField(
            model_name='lobby',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='logo',
            field=models.ImageField(blank=True, upload_to=None),
        ),
        migrations.AlterField(
            model_name='stream',
            name='thumbnail',
            field=models.ImageField(blank=True, upload_to=None),
        ),
    ]
